/**
 * Deploys PrizePool with the Hiero SDK and points the frontend at it.
 *
 * Usage: yarn foundry:deploy [--network testnet|mainnet|local] [--keystore <name>] [--node <id>]
 * Tunables (env): ROUND_SECONDS, DRAW_GRACE_SECONDS, KEEPER_BUFFER_HBAR, MIN_DEPOSIT_HBAR, MAX_PARTICIPANTS,
 *                 DRAW_GAS_LIMIT, TICKET_FEE_HBAR, KEEPER_SEED_HBAR, DEPLOYER_KEYSTORE_PASSWORD
 */
import { AccountId, PrivateKey } from "@hiero-ledger/sdk";
import dotenv from "dotenv";
import { ethers } from "ethers";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import readline from "readline";
import { fileURLToPath } from "url";
import { mirrorGet, networkByName } from "./lib/networks.js";
import { deployPrizePool, prizePoolConfig } from "./lib/prizePool.js";
import { selectOrCreateKeystore } from "./selectOrCreateKeystore.js";

const FOUNDRY_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
dotenv.config({ path: join(FOUNDRY_ROOT, ".env") });

function parseArgs(argv) {
  const args = {
    network: "testnet",
    keystore: process.env.ETH_KEYSTORE_ACCOUNT || undefined,
    node: undefined,
  };
  for (let i = 0; i < argv.length; i += 2) {
    const [flag, value] = [argv[i], argv[i + 1]];
    if (flag === "--network") args.network = value;
    else if (flag === "--keystore") args.keystore = value;
    else if (flag === "--node") args.node = Number(value);
    else
      throw new Error(
        `Unknown option '${flag}'. Usage: yarn foundry:deploy [--network testnet] [--keystore name] [--node id]`
      );
  }
  return args;
}

async function promptHidden(question) {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
  rl._writeToOutput = () => {};
  process.stdout.write(question);
  const answer = await new Promise((resolve) => rl.question("", resolve));
  rl.close();
  process.stdout.write("\n");
  return answer;
}

async function loadDeployer(keystoreName) {
  const path = join(process.env.HOME, ".foundry", "keystores", keystoreName);
  if (!existsSync(path))
    throw new Error(
      `Keystore '${keystoreName}' not found in ~/.foundry/keystores`
    );
  const password =
    process.env.DEPLOYER_KEYSTORE_PASSWORD ??
    (await promptHidden(`🔐 Password for keystore '${keystoreName}': `));
  return ethers.Wallet.fromEncryptedJson(readFileSync(path, "utf8"), password);
}

/** Faucet and wallet accounts are created from their EVM alias; the mirror node maps it back to 0.0.x. */
async function accountIdFor(network, evmAddress) {
  const account = await mirrorGet(network, `/accounts/${evmAddress}`);
  if (!account?.account) {
    throw new Error(
      `No Hedera account for ${evmAddress} on ${network.name}. Fund it at https://portal.hedera.com/faucet first; ` +
        "the first transfer creates the account."
    );
  }
  return AccountId.fromString(account.account);
}

function writeFrontendContracts(network, deployment, deployedOnBlock) {
  const deploymentsDir = join(FOUNDRY_ROOT, "deployments");
  mkdirSync(deploymentsDir, { recursive: true });
  const record = {
    [deployment.address]: "PrizePool",
    contractId: deployment.contractId.toString(),
    networkName: network.name,
  };
  writeFileSync(
    join(deploymentsDir, `${network.chainId}.json`),
    `${JSON.stringify(record, null, 2)}\n`
  );

  const target = join(
    FOUNDRY_ROOT,
    "..",
    "nextjs",
    "contracts",
    "deployedContracts.ts"
  );
  const contract = {
    address: deployment.address,
    abi: deployment.abi,
    inheritedFunctions: {},
    deployedOnBlock,
  };
  writeFileSync(
    target,
    `/**
 * This file is autogenerated by packages/foundry/scripts-js/deployPrizePool.js.
 * Re-run \`yarn foundry:deploy\` instead of editing it by hand.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  ${network.chainId}: {
    PrizePool: ${JSON.stringify(contract, null, 2).replace(/\n/g, "\n    ")},
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
`
  );
  console.log(`   📝 wrote ${target}`);
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const network = networkByName(args.network);
  const stakedNodeId = args.node ?? network.defaultNode;
  const config = prizePoolConfig();

  const keystore = args.keystore ?? (await selectOrCreateKeystore());
  const wallet = await loadDeployer(keystore);
  const operatorId = await accountIdFor(network, wallet.address);
  const client = network
    .client()
    .setOperator(operatorId, PrivateKey.fromStringECDSA(wallet.privateKey));

  console.log(
    `\n🚀 Deploying PrizePool to Hedera ${network.name} as ${operatorId} (${wallet.address})`
  );
  console.log(
    `   round ${config.roundSeconds}s · grace ${config.drawGraceSeconds}s · max ${config.maxParticipants} savers · ` +
      `draw gas ${config.drawGasLimit}`
  );

  try {
    const deployment = await deployPrizePool({ client, stakedNodeId, config });
    const deployedOnBlock = await new ethers.providers.JsonRpcProvider(
      network.rpc
    ).getBlockNumber();
    writeFrontendContracts(network, deployment, deployedOnBlock);

    console.log(
      `\n🎉 PrizePool ${deployment.contractId} (${deployment.address})`
    );
    if (network.hashscan)
      console.log(`   ${network.hashscan}/contract/${deployment.contractId}`);
    console.log(
      `   staking: ${network.mirror}/accounts/${deployment.contractId}\n`
    );
  } finally {
    client.close();
  }
}

main().catch((error) => {
  console.error(`\n❌ ${error.message ?? error}`);
  process.exit(1);
});
