import { mkdirSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const FOUNDRY_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");

/**
 * Records a deployment in `deployments/<chainId>.json` and points the frontend at it by regenerating
 * `packages/nextjs/contracts/deployedContracts.ts` (address + ABI from the forge artifact).
 */
export function writeFrontendContracts(network, deployment, deployedOnBlock) {
  const deploymentsDir = join(FOUNDRY_ROOT, "deployments");
  mkdirSync(deploymentsDir, { recursive: true });
  const record = {
    [deployment.address]: "PrizePool",
    contractId: deployment.contractId.toString(),
    networkName: network.name,
  };
  writeFileSync(
    join(deploymentsDir, `${network.chainId}.json`),
    `${JSON.stringify(record, null, 2)}\n`
  );

  writeDeployedContracts(network.chainId, {
    address: deployment.address,
    abi: deployment.abi,
    deployedOnBlock,
  });
}

/** Regenerates `deployedContracts.ts` for one chain. Also used to refresh the ABI of a placeholder entry. */
export function writeDeployedContracts(
  chainId,
  { address, abi, deployedOnBlock }
) {
  const target = join(
    FOUNDRY_ROOT,
    "..",
    "nextjs",
    "contracts",
    "deployedContracts.ts"
  );
  const contract = { address, abi, inheritedFunctions: {}, deployedOnBlock };
  writeFileSync(
    target,
    `/**
 * This file is autogenerated by packages/foundry/scripts-js/deployPrizePool.js.
 * Re-run \`yarn foundry:deploy\` instead of editing it by hand.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  ${chainId}: {
    PrizePool: ${JSON.stringify(contract, null, 2).replace(/\n/g, "\n    ")},
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
`
  );
  console.log(`   📝 wrote ${target}`);
}
